name: "Publish"
on:
    workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
    publish-dev-container:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            packages: write
        steps:
            - uses: actions/checkout@v3

            - name: "Publish Feature"
              uses: devcontainers/action@v1
              with:
                publish-features: "true"
                base-path-to-features: "./devcontainer-features"
                generate-docs: "true"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    publish-docker-image:
      runs-on: ubuntu-latest
      permissions:
          contents: write
          pull-requests: write
          packages: write
      steps:
        - uses: actions/checkout@v3
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to the Container registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./mcmasterful.Dockerfile
            push: true
            tags: McMastercce/bvd-103-mcmasterful-books
            labels: latest,${{ github.run_id }}


