name: "Publish"
on:
    workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
    publish-dev-container:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            packages: write
        steps:
            - uses: actions/checkout@v3

            - name: "Publish Feature"
              uses: devcontainers/action@v1
              with:
                publish-features: "true"
                base-path-to-features: "./devcontainer-features"
                generate-docs: "true"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    publish-docker-image:
      runs-on: ubuntu-latest
      permissions:
          contents: write
          pull-requests: write
          packages: write
      steps:
        - uses: actions/checkout@v3
        - name: Log in to the Container registry
          uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        - name: Build and push Docker image
          uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
          with:
            context: .
            file: ./mcmasterful.Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}


