name: "Publish Dev-Container Features"
on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            packages: write
        steps:
            - uses: actions/checkout@v3

            - name: "Publish Feature"
              uses: devcontainers/action@v1
              with:
                publish-features: "true"
                base-path-to-features: "./devcontainer-features"
                generate-docs: "true"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
